project:
  type: website
  output-dir: _site
 

website:
  title: "Practical 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Prac1
      - href: prac2.qmd
        text: Prac2
      - href: Prac3.qmd
        text: Prac3
    

format:
  html:
    theme: journal
    mainfont: arial
    fontcolor: "#938d93"
    linkcolor: "#992597"
    css: styles.css
    toc: true
    toc-depth: 3



