project:
  type: website
 

website:
  title: "Practical 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    sidebar: "docked"
        

format:
  html:
    theme: journal
    mainfont: arial
    fontcolor: "#938d93"
    linkcolor: "#992597"
    css: styles.css
    toc: true



