---
title: "Lowess Practical"
editor: visual
---
## Question 1

```{r}
# Generate simulated data 
set.seed(1)
  n<-100
x<-seq(1:n)
head(x)
ei<-rnorm(length(x),mean=0,sd=0.2)
y<- sin(x/10)+ei
head(y)
df7<-data.frame(x,y)

customLowess<-function(x,y,f){
  k=ceiling(f*n)
  smooth_values<-numeric(n)
  for (i in seq_along(x)) {
    # calculate weights
    distLowess<- abs(x-x[i])
    neighbors<-order(distLowess)[1:k]
    Dmax<-max(distLowess[neighbors])
    neighbor_weight <- (1 - (distLowess[neighbors] / Dmax)^3)^3
      #fitting regression 
    X7<- cbind(1,x[neighbors] )
    X7
    W7<-diag(neighbor_weight)
    W7
    Y<-y[neighbors]
    bhat7<-solve(t(X7)%*%W7%*%X7) %*% (t(X7)%*%W7%*%Y)
    bhat7
    smooth_values[i] <- bhat7[1] + bhat7[2] * x[i]
  
  }
  smooth_values
}

plot(df7$x, df7$y, xlab="x", ylab = "y", main ="Lowess from first principles")

lines(customLowess(df7$x,df7$y,0.3), col='blue')

```

## Question 2
Now using Lowess from R.

```{r}
df7<-data.frame(x,y)
plot(df7$x,df7$y, xlab="x", ylab = "y", main = "R Lowess") #Create scatterplot
lines(lowess(df7$x,df7$y,f=0.3), col='red')


```
